name: Horizon Idea
description: Capture a new idea, spike, or experiment proposal.
title: "[IDEA] <short description>"
labels: ["idea", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Map this proposal to n00-frontiers mandates and explain the automation impact.
  - type: input
    id: objective
    attributes:
      label: Objective
      placeholder: "What user/workspace outcome do we unlock?"
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      options: ["Low", "Medium", "High"]
    validations:
      required: true
  - type: textarea
    id: standards
    attributes:
      label: Frontiers references
      description: "List docs/ADRs/templates this idea depends on."
      placeholder: "e.g. docs/workflows/horizons-project-management.md"
    validations:
      required: true
  - type: textarea
    id: automation
    attributes:
      label: Automation target
      description: "Which n00t capability, pipeline, or template should this idea produce?"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance signals
      description: "Define what success looks like (metrics, artefacts, approvals)."
    validations:
      required: true
